import { GetStaticPropsContext } from 'next';
import Head from 'next/head';

import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Trello clone</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://a.trellocdn.com/prgb/dist/images/pinned-tab-icon.8d4bcc6f7600ccbb6675.svg"
        />
      </Head>
    </div>
  );
}

export async function getStaticProps({ locale }: GetStaticPropsContext) {
  return {
    props: {
      messages: (await import(`../locales/${locale}.json`)).default,
    },
  };
}
